

-- ========== bpm_user_group 用户组 ==========
CREATE TABLE IF NOT EXISTS "bpm_user_group" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" smallint NOT NULL,
    "user_ids" varchar(255) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE "bpm_user_group" IS 'BPM 用户组';
COMMENT ON COLUMN "bpm_user_group"."id" IS '编号，自增';
COMMENT ON COLUMN "bpm_user_group"."name" IS '组名';
COMMENT ON COLUMN "bpm_user_group"."description" IS '描述';
COMMENT ON COLUMN "bpm_user_group"."status" IS '状态';
COMMENT ON COLUMN "bpm_user_group"."user_ids" IS '成员用户编号数组';
COMMENT ON COLUMN "bpm_user_group"."creator" IS '创建者';
COMMENT ON COLUMN "bpm_user_group"."create_time" IS '创建时间';
COMMENT ON COLUMN "bpm_user_group"."updater" IS '更新者';
COMMENT ON COLUMN "bpm_user_group"."update_time" IS '更新时间';
COMMENT ON COLUMN "bpm_user_group"."deleted" IS '是否删除';
COMMENT ON COLUMN "bpm_user_group"."tenant_id" IS '租户编号';

-- ========== bpm_category 流程分类 ==========
CREATE TABLE IF NOT EXISTS "bpm_category" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "code" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" smallint NOT NULL,
    "sort" int NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE "bpm_category" IS 'BPM 流程分类';
COMMENT ON COLUMN "bpm_category"."id" IS '分类编号';
COMMENT ON COLUMN "bpm_category"."name" IS '分类名';
COMMENT ON COLUMN "bpm_category"."code" IS '分类标志';
COMMENT ON COLUMN "bpm_category"."description" IS '分类描述';
COMMENT ON COLUMN "bpm_category"."status" IS '分类状态';
COMMENT ON COLUMN "bpm_category"."sort" IS '分类排序';
COMMENT ON COLUMN "bpm_category"."creator" IS '创建者';
COMMENT ON COLUMN "bpm_category"."create_time" IS '创建时间';
COMMENT ON COLUMN "bpm_category"."updater" IS '更新者';
COMMENT ON COLUMN "bpm_category"."update_time" IS '更新时间';
COMMENT ON COLUMN "bpm_category"."deleted" IS '是否删除';
COMMENT ON COLUMN "bpm_category"."tenant_id" IS '租户编号';

-- ========== bpm_form 工作流表单定义 ==========
CREATE TABLE IF NOT EXISTS "bpm_form" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "status" smallint NOT NULL,
    "fields" varchar(255) NOT NULL,
    "conf" varchar(255) NOT NULL,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE "bpm_form" IS 'BPM 工作流表单定义';
COMMENT ON COLUMN "bpm_form"."id" IS '编号';
COMMENT ON COLUMN "bpm_form"."name" IS '表单名';
COMMENT ON COLUMN "bpm_form"."status" IS '状态';
COMMENT ON COLUMN "bpm_form"."fields" IS '表单项的数组';
COMMENT ON COLUMN "bpm_form"."conf" IS '表单的配置';
COMMENT ON COLUMN "bpm_form"."remark" IS '备注';
COMMENT ON COLUMN "bpm_form"."creator" IS '创建者';
COMMENT ON COLUMN "bpm_form"."create_time" IS '创建时间';
COMMENT ON COLUMN "bpm_form"."updater" IS '更新者';
COMMENT ON COLUMN "bpm_form"."update_time" IS '更新时间';
COMMENT ON COLUMN "bpm_form"."deleted" IS '是否删除';
COMMENT ON COLUMN "bpm_form"."tenant_id" IS '租户编号';