-- ========== BPM 模块 H2/MySQL 建表 SQL（测试用） ==========

CREATE TABLE IF NOT EXISTS "bpm_category" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(63) NOT NULL,
    "code"        varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status"      tinyint NOT NULL,
    "sort"        int NOT NULL,
    "creator"     varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '流程分类';

CREATE TABLE IF NOT EXISTS "bpm_user_group" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status"      tinyint NOT NULL,
    "user_ids"    varchar(255) NOT NULL,
    "creator"     varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '用户组';

CREATE TABLE IF NOT EXISTS "bpm_form" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(63) NOT NULL,
    "status"      tinyint NOT NULL,
    "conf"        text NOT NULL,
    "fields"      text NOT NULL,
    "remark"      varchar(255),
    "creator"     varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '动态表单';

CREATE TABLE IF NOT EXISTS "bpm_process_definition_info" (
    "id"                              bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "process_definition_id"           varchar(128) NOT NULL DEFAULT '',
    "model_id"                        varchar(128) NOT NULL DEFAULT '',
    "model_type"                      int,
    "category"                        varchar(128) DEFAULT '',
    "icon"                            varchar(256) DEFAULT '',
    "description"                     varchar(500) DEFAULT '',
    "form_type"                       int,
    "form_id"                         bigint,
    "form_conf"                       text,
    "form_fields"                     text,
    "form_custom_create_path"         varchar(256) DEFAULT '',
    "form_custom_view_path"           varchar(256) DEFAULT '',
    "simple_model"                    text,
    "visible"                         bit DEFAULT TRUE,
    "sort"                            bigint DEFAULT 0,
    "start_user_ids"                  varchar(2048) DEFAULT '',
    "start_dept_ids"                  varchar(2048) DEFAULT '',
    "manager_user_ids"                varchar(2048) DEFAULT '',
    "allow_cancel_running_process"    bit DEFAULT TRUE,
    "allow_withdraw_task"             bit DEFAULT TRUE,
    "process_id_rule"                 text,
    "auto_approval_type"              int,
    "title_setting"                   text,
    "summary_setting"                 text,
    "process_before_trigger_setting"  text,
    "process_after_trigger_setting"   text,
    "task_before_trigger_setting"     text,
    "task_after_trigger_setting"      text,
    "print_template_setting"          text,
    "creator"                         varchar(64) DEFAULT '',
    "create_time"                     timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"                         varchar(64) DEFAULT '',
    "update_time"                     timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"                         bit NOT NULL DEFAULT FALSE,
    "tenant_id"                       bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '流程定义扩展信息';

CREATE TABLE IF NOT EXISTS "bpm_process_expression" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(128) NOT NULL,
    "status"      int NOT NULL,
    "expression"  varchar(1024) DEFAULT '',
    "creator"     varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '流程表达式';

CREATE TABLE IF NOT EXISTS "bpm_process_listener" (
    "id"          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(128) NOT NULL,
    "status"      int NOT NULL,
    "type"        varchar(32) NOT NULL DEFAULT '',
    "event"       varchar(32) NOT NULL DEFAULT '',
    "value_type"  varchar(32) NOT NULL DEFAULT '',
    "value"       varchar(1024) DEFAULT '',
    "creator"     varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '流程监听器';

CREATE TABLE IF NOT EXISTS "bpm_process_instance_copy" (
    "id"                      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "start_user_id"           bigint NOT NULL,
    "process_instance_name"   varchar(128) NOT NULL DEFAULT '',
    "process_instance_id"     varchar(128) NOT NULL DEFAULT '',
    "process_definition_id"   varchar(128) NOT NULL DEFAULT '',
    "category"                varchar(128) DEFAULT '',
    "activity_id"             varchar(128) DEFAULT '',
    "activity_name"           varchar(128) DEFAULT '',
    "task_id"                 varchar(128) DEFAULT '',
    "user_id"                 bigint NOT NULL,
    "reason"                  varchar(1024) DEFAULT '',
    "creator"                 varchar(64) DEFAULT '',
    "create_time"             timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"                 varchar(64) DEFAULT '',
    "update_time"             timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"                 bit NOT NULL DEFAULT FALSE,
    "tenant_id"               bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '流程抄送';
